<?php
/**
 * ScheduleApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Syncro
 *
 * Welcome to the official Syncro API Docs.  To use these docs, you will need an active Syncro account. You can sign up for one here: [Syncro](https://syncromsp.com)  If you already have an active account, fill in your subdomain below and then click \"Authorize\" and fill in your api-key. The key is specific to your user account so it is found on the your user profile page.  Please review the [API License Agreement](https://syncromsp.com/syncromsp-api-license-agreement/) before using our API. By accessing our API, you are agreeing to the API License Agreement.  Please note there is a rate limit of 180 requests per minute per IP address on API Usage.
 *
 * OpenAPI spec version: v1
 * Contact: help@syncromsp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace VereTech\SyncroMSP_PHPclient\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ScheduleApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ScheduleApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for schedulesGet
     *
     * Returns a paginated list of Invoice Schedules.
     *
     */
    public function testSchedulesGet()
    {
    }

    /**
     * Test case for schedulesIdAddLineItemPost
     *
     * Adds a Line Item to an Invoice Schedule.
     *
     */
    public function testSchedulesIdAddLineItemPost()
    {
    }

    /**
     * Test case for schedulesIdDelete
     *
     * Deletes a Schedule by ID.
     *
     */
    public function testSchedulesIdDelete()
    {
    }

    /**
     * Test case for schedulesIdGet
     *
     * Retrieves a Schedule by ID.
     *
     */
    public function testSchedulesIdGet()
    {
    }

    /**
     * Test case for schedulesIdLineItemsScheduleLineItemIdPut
     *
     * Updates a Line Item.
     *
     */
    public function testSchedulesIdLineItemsScheduleLineItemIdPut()
    {
    }

    /**
     * Test case for schedulesIdPut
     *
     * Updates an existing Invoice Schedule by ID.
     *
     */
    public function testSchedulesIdPut()
    {
    }

    /**
     * Test case for schedulesIdRemoveLineItemPost
     *
     * Removes a Line Item from an Invoice Schedule.
     *
     */
    public function testSchedulesIdRemoveLineItemPost()
    {
    }

    /**
     * Test case for schedulesPost
     *
     * Creates an Invoice Schedule.
     *
     */
    public function testSchedulesPost()
    {
    }
}
